"""Plate Splitter — Biocrates 1000 plate layout optimizer."""
from __future__ import annotations

import base64
import io
from typing import Any, Dict, List, Optional, Tuple

import dash
import dash_bootstrap_components as dbc
import numpy as np
import pandas as pd
import plotly.graph_objects as go
from dash import ALL, Input, Output, State, ctx, dash_table, dcc, html

from algorithm import (
    ALL_COLS,
    MAX_SAMPLE_CAPACITY,
    PLATE_ROWS,
    SAMPLE_POSITIONS,
    Plate,
    PlateOptimizer,
    Sample,
    _natural_sort_key,
)
from excel_export import (
    CAL_COLOR,
    EMPTY_COLOR,
    STUDY_COLORS_HEX,
    export_plates_to_excel,
    get_study_color_map,
)
import llm_parser
import biocrates_export

# ── App init ──────────────────────────────────────────────────────────────────

app = dash.Dash(
    __name__,
    external_stylesheets=[dbc.themes.FLATLY],
    title="Plate Splitter",
    # The column-mapping section (apply/cancel buttons, per-column role dropdowns)
    # is generated by render_mapping_section() and isn't present in the initial
    # layout, so Dash's static id-existence check needs to be relaxed for it.
    suppress_callback_exceptions=True,
)
server = app.server  # expose for gunicorn / prod deployments

# ── Constants ─────────────────────────────────────────────────────────────────

# ── Pre-built examples ────────────────────────────────────────────────────────

SIMPLE_EXAMPLE = pd.DataFrame([
    {"sample_id": "S001", "study_id": "StudyA", "repeat_pair": "",   "factor_1": "Female", "factor_2": "Control", "material": "Plasma", "sample_description": "Baseline visit"},
    {"sample_id": "S002", "study_id": "StudyA", "repeat_pair": "",   "factor_1": "Male",   "factor_2": "Control", "material": "Plasma", "sample_description": "Baseline visit"},
    {"sample_id": "S003", "study_id": "StudyA", "repeat_pair": "P1", "factor_1": "Female", "factor_2": "Treated", "material": "Plasma", "sample_description": "Visit 1"},
    {"sample_id": "S004", "study_id": "StudyA", "repeat_pair": "P1", "factor_1": "Female", "factor_2": "Treated", "material": "Plasma", "sample_description": "Visit 2"},
    {"sample_id": "S005", "study_id": "StudyB", "repeat_pair": "",   "factor_1": "Male",   "factor_2": "",        "material": "Serum",  "sample_description": ""},
    {"sample_id": "S006", "study_id": "StudyB", "repeat_pair": "",   "factor_1": "Male",   "factor_2": "",        "material": "Serum",  "sample_description": ""},
])

# Complex example: 4 studies, 440 samples (174+124+65+77), 14 repeat pairs.
# Per-study mode: 7 plates (3+2+1+1). Smart-pack mode: 6 — StudyC and StudyD's
# residuals share a plate, demonstrating both plate-count savings and factor
# balancing across multi-plate studies.
_cx: List[dict] = []
# StudyA – 174 samples: 87 Female + 87 Male singles, no repeat pairs
for i in range(1, 88):
    _cx.append({"sample_id": f"SA{i:03d}", "study_id": "StudyA",
                 "repeat_pair": "", "factor_1": "Female"})
for i in range(88, 175):
    _cx.append({"sample_id": f"SA{i:03d}", "study_id": "StudyA",
                 "repeat_pair": "", "factor_1": "Male"})
# StudyB – 124 samples: 56F + 56M singles + 3 Female pairs + 3 Male pairs
for i in range(1, 57):
    _cx.append({"sample_id": f"SB{i:03d}", "study_id": "StudyB",
                 "repeat_pair": "", "factor_1": "Female"})
for i in range(57, 113):
    _cx.append({"sample_id": f"SB{i:03d}", "study_id": "StudyB",
                 "repeat_pair": "", "factor_1": "Male"})
for i in range(1, 4):   # 3 Female repeat pairs
    _cx.append({"sample_id": f"SB_T1_P{i:02d}", "study_id": "StudyB",
                 "repeat_pair": f"B_pair{i:02d}", "factor_1": "Female"})
    _cx.append({"sample_id": f"SB_T2_P{i:02d}", "study_id": "StudyB",
                 "repeat_pair": f"B_pair{i:02d}", "factor_1": "Female"})
for i in range(4, 7):   # 3 Male repeat pairs
    _cx.append({"sample_id": f"SB_T1_P{i:02d}", "study_id": "StudyB",
                 "repeat_pair": f"B_pair{i:02d}", "factor_1": "Male"})
    _cx.append({"sample_id": f"SB_T2_P{i:02d}", "study_id": "StudyB",
                 "repeat_pair": f"B_pair{i:02d}", "factor_1": "Male"})
# StudyC – 65 samples: 29F + 28M singles + 3 Female pairs + 1 Male pair
for i in range(1, 30):
    _cx.append({"sample_id": f"SC{i:03d}", "study_id": "StudyC",
                 "repeat_pair": "", "factor_1": "Female"})
for i in range(30, 58):
    _cx.append({"sample_id": f"SC{i:03d}", "study_id": "StudyC",
                 "repeat_pair": "", "factor_1": "Male"})
for i in range(1, 4):   # 3 Female repeat pairs
    _cx.append({"sample_id": f"SC_T1_P{i:02d}", "study_id": "StudyC",
                 "repeat_pair": f"C_pair{i:02d}", "factor_1": "Female"})
    _cx.append({"sample_id": f"SC_T2_P{i:02d}", "study_id": "StudyC",
                 "repeat_pair": f"C_pair{i:02d}", "factor_1": "Female"})
_cx.append({"sample_id": "SC_T1_P04", "study_id": "StudyC",   # 1 Male repeat pair
             "repeat_pair": "C_pair04", "factor_1": "Male"})
_cx.append({"sample_id": "SC_T2_P04", "study_id": "StudyC",
             "repeat_pair": "C_pair04", "factor_1": "Male"})
# StudyD – 77 samples: 34F + 35M singles + 2 Female pairs + 2 Male pairs
for i in range(1, 35):
    _cx.append({"sample_id": f"SD{i:03d}", "study_id": "StudyD",
                 "repeat_pair": "", "factor_1": "Female"})
for i in range(35, 70):
    _cx.append({"sample_id": f"SD{i:03d}", "study_id": "StudyD",
                 "repeat_pair": "", "factor_1": "Male"})
for i in range(1, 3):   # 2 Female repeat pairs
    _cx.append({"sample_id": f"SD_T1_P{i:02d}", "study_id": "StudyD",
                 "repeat_pair": f"D_pair{i:02d}", "factor_1": "Female"})
    _cx.append({"sample_id": f"SD_T2_P{i:02d}", "study_id": "StudyD",
                 "repeat_pair": f"D_pair{i:02d}", "factor_1": "Female"})
for i in range(3, 5):   # 2 Male repeat pairs
    _cx.append({"sample_id": f"SD_T1_P{i:02d}", "study_id": "StudyD",
                 "repeat_pair": f"D_pair{i:02d}", "factor_1": "Male"})
    _cx.append({"sample_id": f"SD_T2_P{i:02d}", "study_id": "StudyD",
                 "repeat_pair": f"D_pair{i:02d}", "factor_1": "Male"})

COMPLEX_EXAMPLE = pd.DataFrame(_cx)  # 174 + 124 + 65 + 77 = 440 samples total

# Template for download uses the simple example format
TEMPLATE_DF = SIMPLE_EXAMPLE

TABLE_COLUMNS = [
    {"name": "Sample ID *",        "id": "sample_id",          "editable": True},
    {"name": "Study ID *",         "id": "study_id",           "editable": True},
    {"name": "Repeat Pair",        "id": "repeat_pair",        "editable": True},
    {"name": "Box ID",             "id": "box_id",             "editable": True},
    {"name": "Study Factor 1",     "id": "factor_1",           "editable": True},
    {"name": "Study Factor 2",     "id": "factor_2",           "editable": True},
    {"name": "Biological Matrix",  "id": "material",           "editable": True},
    {"name": "Sample Description", "id": "sample_description", "editable": True},
    {"name": "Sample Alias",       "id": "sample_alias",       "editable": True},
]

# Per-study fields for the Biocrates Sample List CSV export — one row per study,
# auto-synced from the distinct study_ids present in the sample table. Material and
# Sample Description are per-sample (see TABLE_COLUMNS above); Species and Sample
# attributes are set once per study here.
STUDY_META_COLUMNS = [
    {"name": "Study ID",          "id": "study_id",          "editable": False},
    {"name": "Species",           "id": "species",           "editable": True},
    {"name": "Sample attributes", "id": "sample_attributes", "editable": True},
]

# ── Layout helpers ────────────────────────────────────────────────────────────

def _card(header: str, *children: Any, class_name: str = "mb-3") -> dbc.Card:
    return dbc.Card([
        dbc.CardHeader(html.Strong(header)),
        dbc.CardBody(list(children)),
    ], className=class_name)


def _label(text: str) -> html.Label:
    return html.Label(text, className="form-label fw-semibold mt-2")


# ── App layout ────────────────────────────────────────────────────────────────

app.layout = dbc.Container([

    # ── Header ──────────────────────────────────────────────────────────────
    dbc.Row(dbc.Col([
        html.H2("Plate Splitter", className="mt-4 mb-0"),
        html.P(
            "Optimise Biocrates 1000 kit plate layout across studies — "
            "minimise plates, manage batch effects, export coloured plate maps.",
            className="text-muted mb-3",
        ),
    ])),

    dbc.Tabs(id="main-tabs", active_tab="tab-input", children=[

        # ══ Tab 1: Input ════════════════════════════════════════════════════
        dbc.Tab(label="1 · Input", tab_id="tab-input", children=[

            dbc.Row(dbc.Col(
                dbc.Accordion([
                    dbc.AccordionItem([
                        html.P([
                            "Upload or paste your data with ", html.Strong("any"),
                            " column names — after loading, a preview appears below "
                            "the Input cards where you tell the app which of your "
                            "columns is which (Sample ID, Study ID, etc.) before it's "
                            "added to the sample table. A likely mapping is "
                            "pre-selected for you, so well-formed files usually need "
                            "just a glance to confirm.",
                        ], className="mb-2"),
                        html.Ul([
                            html.Li([
                                html.Strong("Sample ID / Study ID"), " — required; map "
                                "exactly one column to each.",
                            ]),
                            html.Li([
                                html.Strong("Repeat Pair"), " — optional group label. "
                                "Rows sharing the same value are treated as one atomic "
                                "unit and are always placed together on the same plate "
                                "(e.g. paired visits, technical replicates). Both rows "
                                "must share the exact same label.",
                            ]),
                            html.Li([
                                html.Strong("Box ID"), " — optional group label for a "
                                "physical storage box (e.g. a freezer box). Samples "
                                "are always picked in box order (box 1 fully before "
                                "box 2, etc. — natural numeric order), so it's a "
                                "simple, predictable sequence to thaw and load from. "
                                "A box isn't forced to fit on one plate — it can span "
                                "the boundary between two adjacent plates — but it "
                                "always continues straight onto the very next plate, "
                                "never skipping around or splitting non-adjacently.",
                            ]),
                            html.Li([
                                html.Strong("Study Factor 1 / Study Factor 2"), " — up "
                                "to two independent stratification variables (e.g. sex, "
                                "treatment arm, timepoint) — map zero, one, or both. "
                                "When 'Balance study factors' is on (Settings tab), "
                                "samples are interleaved so each plate gets a "
                                "proportional mix of every combination.",
                            ]),
                            html.Li([
                                html.Strong("Biological Matrix / Sample Description"),
                                " — optional per-sample fields (e.g. Plasma/Serum/"
                                "Urine, a visit or cohort note) carried straight "
                                "through to the Biocrates Sample List CSV export "
                                "(Export tab). Species and Sample attributes for that "
                                "export are set once per study instead, on the "
                                "Settings tab.",
                            ]),
                            html.Li([
                                html.Strong("Sample Alias"), " — an optional "
                                "alternative name/ID for a sample, e.g. from your "
                                "own tracking sheet. It doesn't appear as the well "
                                "label in the plate view, but shows up on hover, "
                                "and is carried through to the plain sample→plate "
                                "CSV and the Excel Sample List sheet (not the "
                                "Biocrates Sample List export, which is a fixed "
                                "external format).",
                            ]),
                            html.Li([
                                html.Strong("Multi-sheet Excel workbooks"), " — every "
                                "sheet is combined into one preview with an added "
                                "'Sheet Name' column, so you can map Study ID to it if "
                                "your workbook is organised one sheet per study.",
                            ]),
                            html.Li([
                                "For messy or free-form data with no clean column "
                                "structure at all, use the ", html.Strong("Parse with AI"),
                                " switch instead — it skips the mapping step entirely.",
                            ]),
                        ], className="mb-2 small"),
                        html.P(
                            "Unsure what this looks like in practice? Download the "
                            "template CSV or load the 'Simple' example below.",
                            className="text-muted small mb-0",
                        ),
                    ], title="CSV / Excel format reference"),
                ], start_collapsed=True, flush=False, className="mb-3"),
            ), className="mt-3"),

            dbc.Row([
                # Upload card
                dbc.Col(_card(
                    "Upload sample list (CSV or Excel)",
                    dcc.Upload(
                        id="upload-data",
                        children=html.Div([
                            "Drag & drop a file, or ",
                            html.A("click to browse", style={"cursor": "pointer"}),
                        ]),
                        style={
                            "width": "100%", "height": "72px", "lineHeight": "72px",
                            "borderWidth": "2px", "borderStyle": "dashed",
                            "borderRadius": "6px", "textAlign": "center",
                            "borderColor": "#adb5bd", "cursor": "pointer",
                            "background": "#f8f9fa",
                        },
                        multiple=False,
                    ),
                    dbc.FormText(
                        "Multi-sheet workbooks are combined into one preview with a "
                        "'Sheet Name' column — map Study ID to it below if your "
                        "workbook is one sheet per study.",
                        className="d-block mt-1",
                    ),
                    dbc.Switch(
                        id="llm-upload-toggle",
                        label="Parse with AI (unstructured / free-form file)",
                        value=False, className="mt-2",
                    ),
                    dcc.Loading(
                        html.Div(id="upload-status", className="mt-2 text-info small"),
                        type="dot", color="#2C3E50",
                    ),
                    html.Div([
                        dbc.Button(
                            "Download template CSV", id="btn-template",
                            color="secondary", outline=True, size="sm", className="mt-2 me-2",
                        ),
                        dcc.Download(id="download-template"),
                    ]),
                ), width=12, lg=4, className="mt-3"),

                # Paste card
                dbc.Col(_card(
                    "Paste from Excel / spreadsheet",
                    dbc.Textarea(
                        id="paste-area",
                        placeholder=(
                            "Copy cells from Excel and paste here — any columns, "
                            "any order. A header row is optional. You'll choose "
                            "which column is which after pasting."
                        ),
                        rows=5,
                        style={"fontSize": "12px", "fontFamily": "monospace"},
                    ),
                    dbc.Switch(
                        id="llm-parse-toggle",
                        label="Parse with AI (messy / unstructured paste)",
                        value=False, className="mt-2",
                    ),
                    dbc.Row([
                        dbc.Col(
                            dbc.Button("Append to table", id="paste-add-btn",
                                       color="primary", size="sm", n_clicks=0, className="mt-2"),
                            width="auto",
                        ),
                        dbc.Col(
                            dbc.Button("Replace table", id="paste-replace-btn",
                                       color="outline-danger", size="sm", n_clicks=0,
                                       className="mt-2"),
                            width="auto",
                        ),
                    ]),
                    dcc.Loading(
                        html.Div(id="paste-status", className="mt-1 text-info small"),
                        type="dot", color="#2C3E50",
                    ),
                ), width=12, lg=4, className="mt-3"),

                # Quick-add card
                dbc.Col(_card(
                    "Generate sequential IDs",
                    dbc.InputGroup([
                        dbc.Input(id="quick-study", placeholder="Study ID", size="sm"),
                        dbc.Input(id="quick-n", type="number", placeholder="# samples",
                                  min=1, max=500, size="sm"),
                        dbc.Input(id="quick-prefix", placeholder="ID prefix (e.g. S)", size="sm"),
                        dbc.Button("Add study", id="quick-add-btn", color="primary",
                                   size="sm", n_clicks=0),
                    ], size="sm"),
                    dbc.FormText("Creates sample_ids like prefix001, prefix002 …", className="mb-2"),
                ), width=12, lg=4, className="mt-3"),
            ]),

            # Column-mapping preview (shown after a raw upload/paste, before it's committed)
            dbc.Row(dbc.Col(html.Div(id="import-mapping-section"), width=12), className="mt-2"),

            # Sample table
            dbc.Row(dbc.Col(
                dbc.Card([
                    dbc.CardHeader(html.Div([
                        html.Strong("Sample data"),
                        html.Span(" — load example:", className="text-muted small ms-2 me-2"),
                        dbc.Button(
                            "Simple (6 samples, 1 plate)",
                            id="ex-simple-btn", color="outline-primary",
                            size="sm", n_clicks=0, className="me-1",
                        ),
                        dbc.Button(
                            "Complex (440 samples, 4 studies, 14 repeat pairs)",
                            id="ex-complex-btn", color="outline-secondary",
                            size="sm", n_clicks=0,
                        ),
                    ], className="d-flex align-items-center flex-wrap gap-1")),
                    dbc.CardBody([
                        dash_table.DataTable(
                            id="sample-table",
                            columns=TABLE_COLUMNS,
                            data=SIMPLE_EXAMPLE.to_dict("records"),
                            editable=True,
                            row_deletable=True,
                            row_selectable=False,
                            page_action="none",
                            style_table={
                                "overflowX": "auto",
                                "maxHeight": "360px",
                                "overflowY": "auto",
                            },
                            style_cell={"textAlign": "left", "padding": "6px 10px", "fontSize": "13px"},
                            style_header={"fontWeight": "bold", "backgroundColor": "#e9ecef"},
                            style_data_conditional=[
                                {"if": {"row_index": "odd"}, "backgroundColor": "#f8f9fa"},
                            ],
                        ),
                        dbc.Button("+ Add row", id="add-row-btn", color="light",
                                   size="sm", outline=True, className="mt-2"),
                    ]),
                ], className="mb-3"),
            width=12), className="mt-2"),
        ]),

        # ══ Tab 2: Settings ═════════════════════════════════════════════════
        dbc.Tab(label="2 · Settings", tab_id="tab-settings", children=[
            dbc.Row([

                dbc.Col([
                    _card(
                        "Plate settings",
                        dbc.Row([
                            dbc.Col([
                                _label("Sample well capacity (free wells per plate)"),
                                dcc.Slider(
                                    id="plate-capacity",
                                    min=1, max=MAX_SAMPLE_CAPACITY, step=1, value=MAX_SAMPLE_CAPACITY,
                                    marks={i: str(i) for i in
                                           sorted({1, 20, 40, 60, MAX_SAMPLE_CAPACITY})},
                                    tooltip={"placement": "bottom", "always_visible": False},
                                    persistence=True, persistence_type="local",
                                ),
                                dbc.FormText(
                                    f"{MAX_SAMPLE_CAPACITY} is the true maximum (cols 3–12, plus "
                                    f"column 2's 2 free wells, minus 3 always-reserved QC2 wells — "
                                    f"see the QC layout card below). Lower this if fewer wells are "
                                    f"usable for a given run. Plates fill column by column from the "
                                    f"left; any unused capacity is left empty at the end."
                                ),
                            ], width=12, lg=7, className="mb-3 mb-lg-0"),
                            dbc.Col([
                                _label("Random seed (blank = random)"),
                                dbc.Input(id="random-seed", type="number",
                                          placeholder="e.g. 42", size="sm",
                                          persistence=True, persistence_type="local"),
                                dbc.FormText("Fix for reproducible layouts"),
                            ], width=12, lg=5),
                        ], className="mb-3"),
                        dbc.Row([
                            dbc.Col([
                                dbc.Switch(id="allow-mixed", label="Smart-pack studies",
                                           value=False,
                                           persistence=True, persistence_type="local"),
                                dbc.FormText(
                                    "ON (recommended): minimises total plates. Only studies "
                                    "larger than the plate capacity are ever split across "
                                    "plates; their leftover space is offered to smaller "
                                    "studies before opening a new plate. Smaller studies "
                                    "are always kept whole — but two small studies can only share "
                                    "a plate if their combined size fits. "
                                    "OFF: strict isolation — every study gets its own plate(s)."
                                ),
                            ], width=6),
                            dbc.Col([
                                dbc.Switch(id="randomize", label="Randomise sample order",
                                           value=True,
                                           persistence=True, persistence_type="local"),
                                dbc.FormText(
                                    "Shuffle sample order within each study — "
                                    "recommended to reduce within-plate positional effects."
                                ),
                            ], width=6),
                        ], className="mb-3"),
                        dbc.Row([
                            dbc.Col([
                                dbc.Switch(id="balanced-split",
                                           label="Balanced split (multi-plate studies)",
                                           value=True,
                                           persistence=True, persistence_type="local"),
                                dbc.FormText(
                                    "Applies to any study (or, in smart-pack mode, the "
                                    "pooled group of studies) that needs more than one "
                                    "plate. ON: distribute evenly across all those "
                                    "plates. OFF: compact fill (fill one plate to "
                                    "capacity before starting the next). Doesn't affect "
                                    "studies that fit on a single plate — those are "
                                    "always kept whole and bin-packed to minimise gaps, "
                                    "in both modes."
                                ),
                            ], width=6),
                            dbc.Col([
                                dbc.Switch(id="balance-factor",
                                           label="Balance study factors across plates",
                                           value=True,
                                           persistence=True, persistence_type="local"),
                                dbc.FormText(
                                    "Interleave samples by Study Factor 1 × Study Factor 2 "
                                    "combination so each plate receives approximately equal "
                                    "proportions of each combination (stratified randomisation). "
                                    "Has no effect if both factor columns are empty."
                                ),
                            ], width=6),
                        ]),
                    ),
                ], width=12, lg=8),

            ], className="mt-3"),

            dbc.Row([
                dbc.Col([
                    _card(
                        "QC / calibrator layout (fixed)",
                        dbc.FormText([
                            "Column 1 is always booked, top to bottom: ",
                            html.Strong("Blank, PBS, PBS, PBS, Cal1, Cal2, Cal3, Cal4"),
                            ". Column 2 is booked for rows A–F: ",
                            html.Strong("Cal5, Cal6, Cal7, QC1, QC2, QC3"),
                            " — rows G and H are free sample wells. Three extra QC2 "
                            "replicates are also always reserved inside the sample "
                            "area, at ",
                            html.Strong("A6, C9, and E12"),
                            ". All of these show up greyed out in the plate view "
                            "(Results tab) and never receive samples — true usable "
                            "capacity per plate is 79 wells.",
                        ]),
                    ),
                ], width=12, lg=8),
            ], className="mt-3"),

            dbc.Row([
                dbc.Col([
                    _card(
                        "AI-assisted parsing (Ollama)",
                        dbc.Row([
                            dbc.Col([
                                _label("Model"),
                                dcc.Dropdown(
                                    id="llm-model", options=[], value=None,
                                    placeholder="No models found — see status below",
                                    clearable=False,
                                ),
                            ], width=12, lg=6),
                            dbc.Col([
                                _label(" "),
                                html.Div(
                                    dbc.Button("Refresh models", id="llm-refresh-btn",
                                               color="secondary", outline=True, size="sm",
                                               n_clicks=0),
                                ),
                            ], width=12, lg=3),
                        ], className="g-2 align-items-end"),
                        html.Div(id="llm-status", className="mt-2 small"),
                        dbc.FormText(
                            "Used by the 'Parse with AI' switches on the Input tab, for "
                            "pasted text or files that don't follow the expected column "
                            "format (see the format reference above). Runs entirely "
                            "against your local Ollama server — nothing leaves your machine.",
                            className="mt-2",
                        ),
                    ),
                ], width=12, lg=8),
            ], className="mt-3"),

            dbc.Row([
                dbc.Col([
                    _card(
                        "Per-study export metadata",
                        dbc.FormText(
                            "One row per study, auto-detected from the sample table. "
                            "Fills the Species / Sample attributes columns of the "
                            "Biocrates Sample List CSV export (Export tab) — every "
                            "sample in a study gets that study's values. Material and "
                            "Sample Description come from the sample table directly "
                            "(Input tab), since those can vary per sample.",
                            className="mb-2",
                        ),
                        dash_table.DataTable(
                            id="study-meta-table",
                            columns=STUDY_META_COLUMNS,
                            data=[],
                            editable=True,
                            style_table={"overflowX": "auto"},
                            style_cell={"textAlign": "left", "padding": "6px 10px", "fontSize": "13px"},
                            style_header={"fontWeight": "bold", "backgroundColor": "#e9ecef"},
                            style_data_conditional=[
                                {"if": {"row_index": "odd"}, "backgroundColor": "#f8f9fa"},
                            ],
                        ),
                    ),
                ], width=12, lg=8),
            ], className="mt-3"),
        ]),

        # ══ Tab 3: Results ══════════════════════════════════════════════════
        dbc.Tab(label="3 · Results", tab_id="tab-results", children=[
            dbc.Row(dbc.Col([
                dbc.Button(
                    "Run optimisation", id="run-btn",
                    color="primary", size="lg", className="mt-3",
                ),
                dbc.Spinner(
                    html.Div(id="run-error", className="text-danger mt-2"),
                    color="primary", size="sm", spinner_style={"display": "inline-block"},
                ),
            ]), className="mb-3"),

            # Summary KPI cards
            html.Div(id="summary-cards"),

            # Plate map grid
            html.Div(id="plate-maps"),
        ]),

        # ══ Tab 4: Export ═══════════════════════════════════════════════════
        dbc.Tab(label="4 · Export", tab_id="tab-export", children=[
            dbc.Row(dbc.Col(_card(
                "Download results",
                dbc.Row([
                    dbc.Col(
                        dbc.Button("Download Excel plate maps", id="btn-excel",
                                   color="success", className="me-2"),
                        width="auto",
                    ),
                    dbc.Col(
                        dbc.Button("Download CSV (sample → plate mapping)", id="btn-csv",
                                   color="info"),
                        width="auto",
                    ),
                ], className="mb-2"),
                html.Div(id="export-status", className="text-muted small"),
                dcc.Download(id="download-excel"),
                dcc.Download(id="download-csv"),
            ), width=12, lg=6), className="mt-3"),

            dbc.Row(dbc.Col(_card(
                "Biocrates Sample List (MetIDQ import)",
                dbc.FormText(
                    "One CSV per plate (samples only — no calibrator/QC/empty rows), "
                    "zipped together. Sample description and Material come from the "
                    "sample table (Input tab); Species and Sample attributes come from "
                    "the Settings tab's per-study table; the fields below are the same "
                    "on every row of every plate. A 'Sample Alias' column is also "
                    "included, right after Sample Identifier (always present, blank "
                    "where not set) — it's not part of the standard Biocrates/WebIDQ "
                    "column set, so check your import tolerates this extra column.",
                    className="mb-2",
                ),
                dbc.Row([
                    dbc.Col([
                        _label("Cell extr. Volume"),
                        dbc.Input(id="export-cell-volume", type="text", size="sm",
                                  persistence=True, persistence_type="local"),
                    ], width=6, lg=3),
                    dbc.Col([
                        _label("User category (optional)"),
                        dbc.Input(id="export-user-category", type="text", size="sm",
                                  persistence=True, persistence_type="local"),
                    ], width=6, lg=3),
                    dbc.Col([
                        _label("Contact"),
                        dbc.Input(id="export-contact", type="text", size="sm",
                                  persistence=True, persistence_type="local"),
                    ], width=6, lg=3),
                    dbc.Col([
                        _label("Org. info."),
                        dbc.Input(id="export-org-info", type="text", size="sm",
                                  persistence=True, persistence_type="local"),
                    ], width=6, lg=3),
                ], className="mb-2"),
                dbc.Button("Download Sample Lists (zip, 1 CSV/plate)",
                           id="btn-sample-lists", color="success"),
                html.Div(id="sample-list-export-status", className="text-muted small mt-2"),
                dcc.Download(id="download-sample-lists"),
            ), width=12, lg=8), className="mt-3"),
        ]),
    ]),

    # Hidden stores
    dcc.Store(id="plates-store"),
    dcc.Store(id="study-ids-store"),
    dcc.Store(id="raw-import-store"),

], fluid=True)


# ── Callbacks ─────────────────────────────────────────────────────────────────

@app.callback(
    Output("sample-table", "data"),
    Output("upload-status", "children"),
    Output("paste-status", "children"),
    Output("raw-import-store", "data"),
    Input("upload-data", "contents"),
    Input("add-row-btn", "n_clicks"),
    Input("quick-add-btn", "n_clicks"),
    Input("paste-add-btn", "n_clicks"),
    Input("paste-replace-btn", "n_clicks"),
    Input("ex-simple-btn", "n_clicks"),
    Input("ex-complex-btn", "n_clicks"),
    State("upload-data", "filename"),
    State("sample-table", "data"),
    State("quick-study", "value"),
    State("quick-n", "value"),
    State("quick-prefix", "value"),
    State("paste-area", "value"),
    State("llm-upload-toggle", "value"),
    State("llm-parse-toggle", "value"),
    State("llm-model", "value"),
    prevent_initial_call=True,
)
def update_table(
    file_content, _add_click, _quick_click, _paste_add, _paste_replace,
    _ex_simple, _ex_complex,
    filename, current_data, quick_study, quick_n, quick_prefix, paste_text,
    llm_upload_on, llm_paste_on, llm_model,
):
    triggered = ctx.triggered_id
    no_paste = dash.no_update
    no_raw = dash.no_update

    if triggered == "upload-data" and file_content:
        try:
            _, b64 = file_content.split(",", 1)
            decoded = base64.b64decode(b64)
            if llm_upload_on:
                if filename.lower().endswith((".xlsx", ".xls")):
                    text = llm_parser.excel_bytes_to_text(decoded)
                else:
                    text = decoded.decode("utf-8", errors="replace")
                records, msg = llm_parser.parse_with_llm(text, llm_model)
                return (records or (current_data or [])), msg, no_paste, no_raw
            df = _parse_upload_raw(file_content, filename)
            if df.empty:
                return current_data or [], "No data found in file.", no_paste, no_raw
            raw = {"columns": list(df.columns), "records": df.to_dict("records"), "mode": "replace"}
            return (
                dash.no_update,
                f"Loaded {len(df)} rows from {filename} — map columns below.",
                no_paste, raw,
            )
        except Exception as exc:
            return current_data or [], f"Error reading file: {exc}", no_paste, no_raw

    if triggered == "add-row-btn":
        data = list(current_data or [])
        data.append({
            "sample_id": "", "study_id": "", "repeat_pair": "", "box_id": "",
            "factor_1": "", "factor_2": "", "material": "", "sample_description": "",
            "sample_alias": "",
        })
        return data, dash.no_update, no_paste, no_raw

    if triggered == "quick-add-btn":
        if not quick_study or not quick_n:
            return current_data or [], "Provide Study ID and number of samples.", no_paste, no_raw
        prefix = (quick_prefix or "S").strip()
        n = int(quick_n)
        new_rows = [
            {"sample_id": f"{prefix}{i:03d}", "study_id": quick_study.strip(),
             "repeat_pair": "", "box_id": "", "factor_1": "", "factor_2": "", "material": "",
             "sample_description": "", "sample_alias": ""}
            for i in range(1, n + 1)
        ]
        return list(current_data or []) + new_rows, f"Added {n} samples for '{quick_study}'.", no_paste, no_raw

    if triggered == "ex-simple-btn":
        return SIMPLE_EXAMPLE.to_dict("records"), "Simple example loaded.", no_paste, no_raw

    if triggered == "ex-complex-btn":
        return (
            COMPLEX_EXAMPLE.to_dict("records"),
            "Complex example loaded — 440 samples, 4 studies, 14 repeat pairs. "
            "Per-study mode needs 7 plates (3+2+1+1); smart-pack mode needs 6. "
            "Tip: enable 'Balance factor' to distribute Female/Male evenly across plates.",
            no_paste, no_raw,
        )

    if triggered in ("paste-add-btn", "paste-replace-btn"):
        if not paste_text or not paste_text.strip():
            return current_data or [], dash.no_update, "Nothing pasted.", no_raw
        if llm_paste_on:
            records, msg = llm_parser.parse_with_llm(paste_text, llm_model)
            if not records:
                return current_data or [], dash.no_update, msg, no_raw
            base = [] if triggered == "paste-replace-btn" else list(current_data or [])
            return base + records, dash.no_update, msg, no_raw
        mode = "replace" if triggered == "paste-replace-btn" else "append"
        columns, records, msg = _parse_paste_raw(paste_text)
        if not records:
            return current_data or [], dash.no_update, msg, no_raw
        raw = {"columns": columns, "records": records, "mode": mode}
        return dash.no_update, dash.no_update, msg, raw

    return current_data or [], dash.no_update, no_paste, no_raw


@app.callback(
    Output("import-mapping-section", "children"),
    Input("raw-import-store", "data"),
)
def render_mapping_section(raw):
    return _build_mapping_section(raw)


@app.callback(
    Output("sample-table", "data", allow_duplicate=True),
    Output("mapping-status", "children"),
    Output("raw-import-store", "data", allow_duplicate=True),
    Input("apply-mapping-btn", "n_clicks"),
    State({"type": "col-role-dropdown", "index": ALL}, "value"),
    State({"type": "col-role-dropdown", "index": ALL}, "id"),
    State("raw-import-store", "data"),
    State("sample-table", "data"),
    prevent_initial_call=True,
)
def apply_column_mapping(_n_clicks, role_values, role_ids, raw, current_data):
    if not raw or not raw.get("records"):
        return dash.no_update, "Nothing staged to apply.", dash.no_update

    mapping = {
        rid["index"]: val for rid, val in zip(role_ids, role_values) if val and val != "ignore"
    }

    role_counts: Dict[str, int] = {}
    for role in mapping.values():
        role_counts[role] = role_counts.get(role, 0) + 1
    dupes = [r for r, c in role_counts.items() if c > 1]
    if dupes:
        dupe_labels = [o["label"] for o in ROLE_OPTIONS if o["value"] in dupes]
        return (
            dash.no_update,
            f"Each role can only be mapped to one column — duplicated: {', '.join(dupe_labels)}.",
            dash.no_update,
        )

    role_to_col = {role: col for col, role in mapping.items()}
    if "sample_id" not in role_to_col:
        return dash.no_update, "Map a column to Sample ID before applying.", dash.no_update
    if "study_id" not in role_to_col:
        return dash.no_update, "Map a column to Study ID before applying.", dash.no_update

    def get(rec: dict, role: str) -> str:
        col = role_to_col.get(role)
        return str(rec.get(col, "") or "").strip() if col else ""

    new_rows = []
    for rec in raw["records"]:
        sid = get(rec, "sample_id")
        stud = get(rec, "study_id")
        if not sid or not stud:
            continue
        new_rows.append({
            "sample_id": sid,
            "study_id": stud,
            "repeat_pair": get(rec, "repeat_pair"),
            "box_id": get(rec, "box_id"),
            "factor_1": get(rec, "factor_1"),
            "factor_2": get(rec, "factor_2"),
            "material": get(rec, "material"),
            "sample_description": get(rec, "sample_description"),
            "sample_alias": get(rec, "sample_alias"),
        })

    if not new_rows:
        return (
            dash.no_update,
            "No valid rows after mapping — every row needs a Sample ID and Study ID.",
            dash.no_update,
        )

    base = [] if raw.get("mode") == "replace" else list(current_data or [])
    return base + new_rows, f"Loaded {len(new_rows)} samples.", None


@app.callback(
    Output("raw-import-store", "data", allow_duplicate=True),
    Input("cancel-mapping-btn", "n_clicks"),
    prevent_initial_call=True,
)
def cancel_mapping(_n_clicks):
    return None


@app.callback(
    Output("llm-model", "options"),
    Output("llm-model", "value"),
    Output("llm-status", "children"),
    Input("llm-refresh-btn", "n_clicks"),
)
def refresh_llm_models(_n_clicks):
    """Populates the model dropdown on page load and on manual refresh."""
    models = llm_parser.list_models()
    if not models:
        status = html.Span(
            f"Ollama not reachable at {llm_parser.OLLAMA_HOST}. Start it with "
            f"`ollama serve`, and make sure a model is pulled (e.g. "
            f"`ollama pull llama3.1`), then click Refresh.",
            className="text-danger",
        )
        return [], None, status
    options = [{"label": m, "value": m} for m in models]
    status = html.Span(f"{len(models)} model(s) available.", className="text-success")
    return options, models[0], status


@app.callback(
    Output("download-template", "data"),
    Input("btn-template", "n_clicks"),
    prevent_initial_call=True,
)
def download_template(_):
    return dcc.send_data_frame(TEMPLATE_DF.to_csv, "plate_splitter_template.csv", index=False)


@app.callback(
    Output("plates-store", "data"),
    Output("study-ids-store", "data"),
    Output("run-error", "children"),
    Output("summary-cards", "children"),
    Output("plate-maps", "children"),
    Input("run-btn", "n_clicks"),
    State("sample-table", "data"),
    State("plate-capacity", "value"),
    State("allow-mixed", "value"),
    State("randomize", "value"),
    State("balanced-split", "value"),
    State("balance-factor", "value"),
    State("random-seed", "value"),
    prevent_initial_call=True,
)
def run_optimisation(
    _n_clicks, table_data, capacity, allow_mixed, randomize,
    balanced, balance_factor, seed,
):
    _no = dash.no_update

    # ── Parse table ──────────────────────────────────────────────────────────
    if not table_data:
        return _no, _no, "No sample data found.", _no, _no

    df = pd.DataFrame(table_data)
    df["sample_id"] = df["sample_id"].astype(str).str.strip()
    df["study_id"]  = df["study_id"].astype(str).str.strip()
    df = df[df["sample_id"].ne("") & df["study_id"].ne("") &
            df["sample_id"].ne("nan") & df["study_id"].ne("nan")]

    if df.empty:
        return _no, _no, "No valid samples found.", _no, _no

    dupes = df["sample_id"][df["sample_id"].duplicated()].unique().tolist()
    if dupes:
        return (
            _no, _no,
            f"Duplicate Sample IDs: {', '.join(dupes[:5])}{'…' if len(dupes) > 5 else ''}",
            _no, _no,
        )

    # ── Build studies ────────────────────────────────────────────────────────
    def _clean(row, key: str) -> Optional[str]:
        v = str(row.get(key, "") or "").strip()
        return v if v and v != "nan" else None

    study_groups: Dict[str, List[Sample]] = {}
    for _, row in df.iterrows():
        s = Sample(
            sample_id=row["sample_id"],
            study_id=row["study_id"],
            repeat_pair=_clean(row, "repeat_pair"),
            box_id=_clean(row, "box_id"),
            factor_1=_clean(row, "factor_1"),
            factor_2=_clean(row, "factor_2"),
            material=_clean(row, "material"),
            sample_description=_clean(row, "sample_description"),
            sample_alias=_clean(row, "sample_alias"),
        )
        study_groups.setdefault(row["study_id"], []).append(s)

    study_ids = list(study_groups.keys())

    # ── Run optimiser ────────────────────────────────────────────────────────
    try:
        opt = PlateOptimizer(
            plate_capacity=int(capacity or MAX_SAMPLE_CAPACITY),
            allow_mixed=bool(allow_mixed),
            randomize=bool(randomize) if randomize is not None else True,
            balanced=bool(balanced) if balanced is not None else True,
            balance_factor=bool(balance_factor) if balance_factor is not None else True,
            seed=int(seed) if seed is not None else None,
        )
        plates = opt.optimize(list(study_groups.values()))
    except ValueError as exc:
        return _no, _no, str(exc), _no, _no

    plates_json = [p.serialize() for p in plates]
    color_map = get_study_color_map(study_ids)

    # ── Summary KPIs ─────────────────────────────────────────────────────────
    n_plates   = len(plates)
    n_samples  = len(df)
    efficiency = n_samples / (n_plates * int(capacity or MAX_SAMPLE_CAPACITY)) * 100 if n_plates else 0
    multi_plate_studies = [
        sid for sid in study_ids
        if sum(
            1 for p in plates
            if any(w.study_id == sid for w in p.wells.values() if w.well_type == "sample")
        ) > 1
    ]

    # Study factor summary across all plates
    all_factor1_levels = sorted({
        w.factor_1 for p in plates for w in p.wells.values()
        if w.well_type == "sample" and w.factor_1
    })
    all_factor2_levels = sorted({
        w.factor_2 for p in plates for w in p.wells.values()
        if w.well_type == "sample" and w.factor_2
    })
    has_factor = bool(all_factor1_levels or all_factor2_levels)

    alerts = []
    if multi_plate_studies:
        alerts.append(dbc.Alert(
            f"Studies spanning multiple plates: {', '.join(multi_plate_studies)}. "
            "Consider adding pooled bridging/QC samples as rows in your sample list "
            "to help correct for between-plate batch effects.",
            color="warning", className="mb-2",
        ))

    if has_factor and balance_factor:
        factor_parts = []
        if all_factor1_levels:
            factor_parts.append(f"Factor 1: {', '.join(all_factor1_levels)}")
        if all_factor2_levels:
            factor_parts.append(f"Factor 2: {', '.join(all_factor2_levels)}")
        alerts.append(dbc.Alert(
            f"Study factor levels detected — {'; '.join(factor_parts)}. "
            "Samples were interleaved by factor combination across plates.",
            color="info", className="mb-2",
        ))

    factor1_shape_map = _build_factor_shape_map(all_factor1_levels) if all_factor1_levels else {}
    factor2_shape_map = _build_factor_shape_map(all_factor2_levels) if all_factor2_levels else {}

    kpi_cards = html.Div([
        dbc.Row([
            _kpi("Plates used",           str(n_plates),            "primary"),
            _kpi("Samples",               str(n_samples),           "secondary"),
            _kpi("Efficiency",            f"{efficiency:.0f}%",     "success"),
            _kpi("Multi-plate studies",   str(len(multi_plate_studies)), "warning"),
        ], className="mb-3 g-2"),
        *alerts,
        _factor_legend(factor1_shape_map, factor2_shape_map),
    ])

    # ── Plate maps ───────────────────────────────────────────────────────────
    from collections import Counter

    plate_figs = []
    for plate in plates:
        fig = _plate_figure(plate, color_map, factor1_shape_map, factor2_shape_map)
        sample_wells = [w for w in plate.wells.values() if w.well_type == "sample"]
        n_s = len(sample_wells)
        studies_here = sorted({w.study_id for w in sample_wells if w.study_id})

        # One row per study on this plate — keeps each study's own sample/pair/box/
        # factor breakdown separate rather than aggregating across a shared plate.
        study_rows = []
        for sid in studies_here:
            study_wells = [w for w in sample_wells if w.study_id == sid]
            n_study = len(study_wells)
            n_paired_study = sum(1 for w in study_wells if w.repeat_pair)
            boxes_study = sorted(
                {w.box_id for w in study_wells if w.box_id}, key=_natural_sort_key
            )

            parts = [f"{n_study} samples"]
            if n_paired_study:
                parts.append(f"{n_paired_study} in repeat pairs")
            if boxes_study:
                parts.append(f"box(es): {', '.join(boxes_study)}")

            factor_bits = []
            for label, attr in (("F1", "factor_1"), ("F2", "factor_2")):
                counts = Counter(getattr(w, attr) for w in study_wells if getattr(w, attr))
                if counts:
                    counts_str = " | ".join(f"{k}: {v}" for k, v in sorted(counts.items()))
                    factor_bits.append(f"{label} {counts_str}")

            swatch = "#" + color_map.get(sid, "CCCCCC")
            study_rows.append(
                html.P([
                    html.Span(style={
                        "display": "inline-block", "width": "9px", "height": "9px",
                        "borderRadius": "50%", "backgroundColor": swatch,
                        "marginRight": "6px",
                    }),
                    html.Strong(sid), " — ", ", ".join(parts),
                    (f"  ·  {'; '.join(factor_bits)}" if factor_bits else ""),
                ], className="small text-muted mb-0"),
            )

        plate_figs.append(
            dbc.Col([
                html.H6(f"Plate {plate.plate_number}", className="mb-0 mt-2"),
                html.P(f"{n_s} samples total", className="text-muted small mb-1"),
                html.Div(study_rows, className="mb-1"),
                dcc.Graph(figure=fig, config={"displayModeBar": False},
                          style={"height": "290px"}),
            ], width=12, lg=6, xl=4)
        )

    return plates_json, study_ids, "", kpi_cards, dbc.Row(plate_figs)


@app.callback(
    Output("download-excel", "data"),
    Output("export-status", "children"),
    Input("btn-excel", "n_clicks"),
    State("plates-store", "data"),
    State("study-ids-store", "data"),
    prevent_initial_call=True,
)
def download_excel(_n_clicks, plates_json, study_ids):
    if not plates_json:
        return dash.no_update, "Run optimisation first (tab 3)."
    plates = [Plate.deserialize(d) for d in plates_json]
    data = export_plates_to_excel(plates, study_ids or [])
    return dcc.send_bytes(data, "plate_maps.xlsx"), ""


@app.callback(
    Output("download-csv", "data"),
    Input("btn-csv", "n_clicks"),
    State("plates-store", "data"),
    prevent_initial_call=True,
)
def download_csv(_n_clicks, plates_json):
    if not plates_json:
        return dash.no_update
    plates = [Plate.deserialize(d) for d in plates_json]
    frames = [p.to_dataframe() for p in plates]
    df = pd.concat(frames, ignore_index=True)
    df = df[df["well_type"] == "sample"].drop(columns=["box_id"])
    return dcc.send_data_frame(df.to_csv, "sample_plate_mapping.csv", index=False)


@app.callback(
    Output("study-meta-table", "data"),
    Input("sample-table", "data"),
    State("study-meta-table", "data"),
)
def sync_study_meta(sample_data, meta_data):
    """Keeps one metadata row per distinct study_id in the sample table, preserving
    already-entered values and dropping rows for studies no longer present."""
    study_ids = []
    seen = set()
    for row in (sample_data or []):
        sid = str(row.get("study_id", "") or "").strip()
        if sid and sid not in ("nan",) and sid not in seen:
            seen.add(sid)
            study_ids.append(sid)

    existing = {r["study_id"]: r for r in (meta_data or [])}
    return [
        existing.get(sid, {"study_id": sid, "species": "", "sample_attributes": ""})
        for sid in study_ids
    ]


@app.callback(
    Output("download-sample-lists", "data"),
    Output("sample-list-export-status", "children"),
    Input("btn-sample-lists", "n_clicks"),
    State("plates-store", "data"),
    State("study-meta-table", "data"),
    State("export-cell-volume", "value"),
    State("export-user-category", "value"),
    State("export-contact", "value"),
    State("export-org-info", "value"),
    prevent_initial_call=True,
)
def download_sample_lists(_n_clicks, plates_json, meta_data, cell_vol, user_cat, contact, org_info):
    if not plates_json:
        return dash.no_update, "Run optimisation first (tab 3)."
    plates = [Plate.deserialize(d) for d in plates_json]
    study_meta = {r["study_id"]: r for r in (meta_data or [])}
    globals_ = {
        "cell_extr_volume": cell_vol or "",
        "user_category": user_cat or "",
        "contact": contact or "",
        "org_info": org_info or "",
    }
    data = biocrates_export.export_sample_lists_zip(plates, study_meta, globals_)
    return (
        dcc.send_bytes(data, "biocrates_sample_lists.zip"),
        f"{len(plates)} CSV file(s) zipped.",
    )


# ── Visualisation helpers ─────────────────────────────────────────────────────

# Well fill = study (color_map). Factor levels are marked with small corner glyphs
# instead of color, so they read clearly against any study's fill: Factor 1 = white
# marker, top-left corner; Factor 2 = black marker, bottom-right corner. Shape (not
# color) carries the level within each factor, so it stays legible in this two-tone
# scheme and doesn't compete with the study color palette.
FACTOR_MARKER_SYMBOLS = [
    "circle", "square", "diamond", "triangle-up", "triangle-down", "star", "cross", "hexagon",
]
FACTOR_MARKER_GLYPHS = {
    "circle": "●", "square": "■", "diamond": "◆", "triangle-up": "▲",
    "triangle-down": "▼", "star": "★", "cross": "✚", "hexagon": "⬡",
}


def _build_factor_shape_map(levels: List[str]) -> Dict[str, str]:
    return {lvl: FACTOR_MARKER_SYMBOLS[i % len(FACTOR_MARKER_SYMBOLS)] for i, lvl in enumerate(sorted(levels))}


def _factor_legend(factor1_shapes: Dict[str, str], factor2_shapes: Dict[str, str]) -> Optional[html.Div]:
    if not factor1_shapes and not factor2_shapes:
        return None
    parts = []
    if factor1_shapes:
        items = "   ".join(f"{FACTOR_MARKER_GLYPHS[s]} {lvl}" for lvl, s in factor1_shapes.items())
        parts.append(html.Span([html.Strong("Factor 1 (○ top-left): "), items], className="me-4"))
    if factor2_shapes:
        items = "   ".join(f"{FACTOR_MARKER_GLYPHS[s]} {lvl}" for lvl, s in factor2_shapes.items())
        parts.append(html.Span([html.Strong("Factor 2 (● bottom-right): "), items]))
    return html.Div(parts, className="small text-muted mb-2")


def _plate_figure(
    plate: Plate,
    color_map: Dict[str, str],
    factor1_shapes: Optional[Dict[str, str]] = None,
    factor2_shapes: Optional[Dict[str, str]] = None,
) -> go.Figure:
    """Build a plotly heatmap of a 96-well plate (8 rows × 12 cols)."""
    factor1_shapes = factor1_shapes or {}
    factor2_shapes = factor2_shapes or {}
    # Category list determines color order
    base = ["empty", "calibrator"]
    studies = sorted(color_map.keys())
    categories = base + studies
    n = len(categories)

    hex_colors = (
        ["#FFFFFF", "#CCCCCC"]
        + ["#" + color_map.get(s, "CCCCCC") for s in studies]
    )

    # Discrete colorscale: each category occupies band [i/n, (i+1)/n]
    colorscale: List[List] = []
    for i, c in enumerate(hex_colors):
        colorscale.append([i / n, c])
        colorscale.append([(i + 1) / n, c])

    cat_idx = {c: i for i, c in enumerate(categories)}

    z = np.zeros((8, 12))
    text_grid = [[""] * 12 for _ in range(8)]
    hover_grid = [[""] * 12 for _ in range(8)]
    f1_x: List[float] = []; f1_y: List[float] = []; f1_symbol: List[str] = []
    f2_x: List[float] = []; f2_y: List[float] = []; f2_symbol: List[str] = []

    for r_i, row in enumerate(PLATE_ROWS):
        for c_i, col in enumerate(ALL_COLS):
            w = plate.wells[(row, col)]
            wtype = w.well_type

            if wtype == "calibrator":
                cat = "calibrator"
                disp = w.label or "CAL"
                hov = f"{row}{col}: {w.label or 'Calibrator'}"
            elif wtype == "empty":
                cat = "empty"
                disp = ""
                hov = f"{row}{col}: Empty"
            else:
                cat = w.study_id or "empty"
                sid = w.sample_id or ""
                disp = sid[:9] + "…" if len(sid) > 9 else sid
                hov = f"{row}{col}: {w.study_id} — {w.sample_id}"
                if w.sample_alias:
                    hov += f" (alias: {w.sample_alias})"
                factors = [f for f in (w.factor_1, w.factor_2) if f]
                if factors:
                    hov += f" [{', '.join(factors)}]"
                if w.repeat_pair:
                    hov += f" (pair: {w.repeat_pair})"
                if w.box_id:
                    hov += f" (box: {w.box_id})"

                if w.factor_1 in factor1_shapes:
                    f1_x.append(c_i - 0.32); f1_y.append(r_i - 0.32)
                    f1_symbol.append(factor1_shapes[w.factor_1])
                if w.factor_2 in factor2_shapes:
                    f2_x.append(c_i + 0.32); f2_y.append(r_i + 0.32)
                    f2_symbol.append(factor2_shapes[w.factor_2])

            k = cat_idx.get(cat, 0)
            z[r_i][c_i] = (k + 0.5) / n
            text_grid[r_i][c_i] = disp
            hover_grid[r_i][c_i] = hov

    fig = go.Figure(go.Heatmap(
        z=z,
        text=text_grid,
        customdata=hover_grid,
        hovertemplate="%{customdata}<extra></extra>",
        texttemplate="%{text}",
        textfont={"size": 7},
        colorscale=colorscale,
        showscale=False,
        xgap=2, ygap=2,
        zmin=0, zmax=1,
    ))

    if f1_x:
        fig.add_trace(go.Scatter(
            x=f1_x, y=f1_y, mode="markers",
            marker=dict(symbol=f1_symbol, size=6, color="white",
                        line=dict(color="black", width=1)),
            hoverinfo="skip", showlegend=False,
        ))
    if f2_x:
        fig.add_trace(go.Scatter(
            x=f2_x, y=f2_y, mode="markers",
            marker=dict(symbol=f2_symbol, size=6, color="black",
                        line=dict(color="white", width=1)),
            hoverinfo="skip", showlegend=False,
        ))

    fig.update_layout(
        xaxis=dict(
            tickmode="array",
            tickvals=list(range(12)),
            ticktext=[str(c) for c in ALL_COLS],
            side="top",
            showgrid=False,
            fixedrange=True,
        ),
        yaxis=dict(
            tickmode="array",
            tickvals=list(range(8)),
            ticktext=PLATE_ROWS,
            autorange="reversed",
            showgrid=False,
            fixedrange=True,
        ),
        margin=dict(t=50, b=5, l=30, r=5),
        plot_bgcolor="white",
        paper_bgcolor="white",
    )
    return fig


def _kpi(label: str, value: str, color: str) -> dbc.Col:
    return dbc.Col(
        dbc.Card([
            dbc.CardBody([
                html.H4(value, className="mb-0"),
                html.Small(label, className="text-muted"),
            ], className="text-center py-2"),
        ], color=color, outline=True),
        width=6, sm=4, md=2,
    )


def _dedupe_columns(cols: List[str]) -> List[str]:
    """Keep column names unique (needed since they double as Dash component ids
    in the mapping UI) by suffixing repeats: 'Notes', 'Notes (2)', 'Notes (3)', ..."""
    seen: Dict[str, int] = {}
    out = []
    for c in cols:
        if c not in seen:
            seen[c] = 1
            out.append(c)
        else:
            seen[c] += 1
            out.append(f"{c} ({seen[c]})")
    return out


def _parse_paste_raw(text: str) -> Tuple[List[str], List[dict], str]:
    """Parse tab- or comma-separated pasted text into raw (un-mapped) records —
    role assignment happens later via the column-mapping UI."""
    lines = [l for l in text.strip().splitlines() if l.strip()]
    if not lines:
        return [], [], "Nothing to parse."

    delim = "\t" if "\t" in lines[0] else ","
    rows_raw = [[c.strip() for c in line.split(delim)] for line in lines]

    first_lower = [c.lower() for c in rows_raw[0]]
    has_header = any("sample" in c or "study" in c for c in first_lower)

    if has_header:
        headers = _dedupe_columns([c.strip() for c in rows_raw[0]])
        data_rows = rows_raw[1:]
    else:
        headers = [f"Column {i + 1}" for i in range(len(rows_raw[0]))]
        data_rows = rows_raw

    records = []
    for row in data_rows:
        if not any(c for c in row):
            continue
        records.append({h: (row[i].strip() if i < len(row) else "") for i, h in enumerate(headers)})

    if not records:
        return headers, [], "Nothing to parse."
    return headers, records, f"Parsed {len(records)} rows — map columns below."


def _parse_multi_sheet_excel_raw(xls: pd.ExcelFile) -> pd.DataFrame:
    """Combine every sheet, keeping original columns, plus a 'Sheet Name' helper
    column so Study ID can be mapped to it if the workbook is one sheet per study."""
    frames = []
    for sheet_name in xls.sheet_names:
        sheet_df = xls.parse(sheet_name)
        if sheet_df.empty:
            continue
        sheet_df = sheet_df.copy()
        sheet_df["Sheet Name"] = sheet_name.strip()
        frames.append(sheet_df)
    if not frames:
        raise ValueError("The workbook has no data in any sheet.")
    return pd.concat(frames, ignore_index=True)


def _parse_upload_raw(content: str, filename: str) -> pd.DataFrame:
    """Parse an uploaded file into a raw DataFrame with its own original column
    headers — role assignment happens later via the column-mapping UI."""
    _, b64 = content.split(",", 1)
    decoded = base64.b64decode(b64)
    if filename.lower().endswith((".xlsx", ".xls")):
        xls = pd.ExcelFile(io.BytesIO(decoded))
        if len(xls.sheet_names) > 1:
            df = _parse_multi_sheet_excel_raw(xls)
        else:
            df = xls.parse(xls.sheet_names[0])
    else:
        df = pd.read_csv(io.StringIO(decoded.decode("utf-8", errors="replace")))
    df.columns = _dedupe_columns([str(c).strip() for c in df.columns])
    return df.fillna("")


# ── Column mapping (upload/paste preview → sample-table roles) ─────────────────

ROLE_OPTIONS = [
    {"label": "Ignore",              "value": "ignore"},
    {"label": "Sample ID",           "value": "sample_id"},
    {"label": "Study ID",            "value": "study_id"},
    {"label": "Repeat Pair",         "value": "repeat_pair"},
    {"label": "Box ID",              "value": "box_id"},
    {"label": "Study Factor 1",      "value": "factor_1"},
    {"label": "Study Factor 2",      "value": "factor_2"},
    {"label": "Biological Matrix",   "value": "material"},
    {"label": "Sample Description",  "value": "sample_description"},
    {"label": "Sample Alias",        "value": "sample_alias"},
]

# Keyword groups tried in order per role, to pre-select a best-guess mapping.
# 'factor 1' / 'factor 2' are checked before the generic 'factor' fallback so an
# explicitly-numbered header wins over an ambiguous single-factor one. Likewise,
# sample_alias's specific keywords are checked before sample_id's broad "sample"
# fallback, so a "Sample Alias" header can't get claimed by sample_id first.
_ROLE_KEYWORDS: List[Tuple[str, Tuple[str, ...]]] = [
    ("sample_alias",       ("sample_alias", "sample alias", "alias")),
    ("sample_id",          ("sample_id", "sample id", "sample")),
    ("study_id",           ("study_id", "study id", "study", "sheet name", "sheet_name")),
    ("repeat_pair",        ("repeat_pair", "repeat pair", "repeat", "pair")),
    ("box_id",             ("box_id", "box id", "box", "vial box", "freezer box")),
    ("factor_1",           ("factor_1", "factor 1", "study factor 1", "biological_factor",
                             "biological factor", "factor", "group", "sex", "condition", "treatment")),
    ("factor_2",           ("factor_2", "factor 2", "study factor 2")),
    ("material",           ("material", "biological_matrix", "biological matrix", "matrix")),
    ("sample_description", ("sample_description", "sample description", "description")),
]


def _guess_column_roles(headers: List[str]) -> Dict[str, str]:
    """Best-guess {header: role} for as many headers as confidently match; headers
    with no confident match are left unmapped (default to 'ignore' in the UI)."""
    lowered = {h: h.strip().lower() for h in headers}
    used: set = set()
    roles: Dict[str, str] = {}
    for role, keywords in _ROLE_KEYWORDS:
        for kw in keywords:
            match = next((h for h in headers if h not in used and kw in lowered[h]), None)
            if match:
                roles[match] = role
                used.add(match)
                break
    return roles


def _build_mapping_section(raw: Optional[dict]) -> Optional[dbc.Card]:
    if not raw or not raw.get("columns"):
        return None
    columns = raw["columns"]
    records = raw["records"]
    guesses = _guess_column_roles(columns)

    preview_table = dash_table.DataTable(
        columns=[{"name": c, "id": c} for c in columns],
        data=records[:100],
        style_table={"overflowX": "auto", "maxHeight": "260px", "overflowY": "auto"},
        style_cell={"textAlign": "left", "padding": "4px 8px", "fontSize": "12px"},
        style_header={"fontWeight": "bold", "backgroundColor": "#e9ecef"},
    )
    preview_note = (
        f" (showing first 100 of {len(records)} rows — all {len(records)} will be loaded)"
        if len(records) > 100 else ""
    )

    mapping_rows = [
        dbc.Row([
            dbc.Col(html.Div(c, className="small fw-semibold text-truncate", title=c), width=4),
            dbc.Col(
                dcc.Dropdown(
                    id={"type": "col-role-dropdown", "index": c},
                    options=ROLE_OPTIONS,
                    value=guesses.get(c, "ignore"),
                    clearable=False,
                ),
                width=8,
            ),
        ], className="mb-1 align-items-center")
        for c in columns
    ]

    return _card(
        "Map columns before loading",
        html.P(
            f"{len(records)} row(s) parsed{preview_note}. Review the preview, then "
            "confirm or change which column is which — a likely mapping is "
            "pre-selected.",
            className="small text-muted mb-2",
        ),
        preview_table,
        html.Div(mapping_rows, className="mt-3 mb-2"),
        dbc.Row([
            dbc.Col(dbc.Button("Apply mapping — load samples", id="apply-mapping-btn",
                                color="primary", size="sm", n_clicks=0), width="auto"),
            dbc.Col(dbc.Button("Cancel", id="cancel-mapping-btn",
                                color="secondary", outline=True, size="sm", n_clicks=0),
                    width="auto"),
        ], className="g-2"),
        html.Div(id="mapping-status", className="mt-2 small"),
    )


# ── Entry point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    app.run(debug=True, port=8050)
